config/routes.rb
F4::Application.routes.draw do

  devise_for :users

  resources :badges

  resources :users

  resources :tags

  resources :sentences

  resources :words

  resources :lookups

  resources :courses do
    resources :units
    resources :course_sessions
  end
  
  resources :course_sessions do
    resources :course_session_enrollments
  end
  
  
  resources :units do
    resources :lessons
  end
  
  resources :lessons do
    resources :lesson_layouts
  end
  
  resources :lesson_layouts do
    resources :layout_fields
    resources :layout_tables
  end
  
  resources :media_catagories do
     resources :media
   end
    
  root :to => 'courses#index'

end

app/models/badge.rb
class Badge < ActiveRecord::Base
  attr_accessible :badge_name
end

app/models/course.rb
class Course < ActiveRecord::Base
  attr_accessible :course_language, :course_name, :course_type, :description, :owner, :status, :synopsis, :target_level, :version
  has_many :units, :dependent => :destroy
  has_many :course_sessions, :dependent => :destroy
end

app/models/layout_field.rb
class LayoutField < ActiveRecord::Base
  belongs_to :lesson_layout
  attr_accessible :field_name, :field_value, :version, :lesson_layout_id
end

app/models/layout_table.rb
class LayoutTable < ActiveRecord::Base
  belongs_to :lesson_layout
  attr_accessible :col1, :col2, :col3, :col4, :row_num, :table_number, :version, :lesson_layout_id
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :unit
  has_many :lesson_layouts, :dependent => :destroy
  attr_accessible :description, :lesson_name, :lesson_type, :seq, :status, :synopsis, :version, :unit_id
end

app/models/lesson_layout.rb
class LessonLayout < ActiveRecord::Base
  belongs_to :lesson
  has_many :layout_fields, :dependent => :destroy
  has_many :layout_tables, :dependent => :destroy
  attr_accessible :device_type, :layout_type, :seq, :version, :lesson_id
end

app/models/lookup.rb
class Lookup < ActiveRecord::Base
  attr_accessible :field_name, :lookup_text, :note, :model_name
  
end

app/models/media.rb
class Media < ActiveRecord::Base
  belongs_to :media_catagory
  has_many :media_sentence_xrefs
  has_many :sentences, :through => :media_sentence_xrefs
  attr_accessible :seq, :description, :file_bitmap, :media_filename, :media_name, :media_catagory_id
end

app/models/sentence.rb
class Sentence < ActiveRecord::Base
  has_many :media_sentence_xrefs
  has_many :media, :through => :media_sentence_xrefs
  has_many :sentence_tag_xrefs
  has_many :tags, :through => :sentence_tag_xrefs
  attr_accessible :language, :sentence
end

app/models/sentence_tag.rb
class SentenceTag < ActiveRecord::Base
  belongs_to :sentence
  attr_accessible :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :sentence_tag_xrefs
  has_many :sentences, :through => :sentence_tag_xrefs
  attr_accessible :tag, :tag_system_bitmap, :tag_type
end

app/models/unit.rb
class Unit < ActiveRecord::Base
  belongs_to :course
  #has_many :unit_layouts, :dependent => :destroy
  has_many :lessons, :dependent => :destroy
  attr_accessible :description, :seq, :status, :synopsis, :unit_name, :unit_type, :version, :course_id
end

app/models/unit_layout.rb
class UnitLayout < ActiveRecord::Base
  belongs_to :unit
  has_many :layout_fields, :dependent => :destroy
  has_many :layout_tables, :dependent => :destroy
  attr_accessible :device_type, :layout_type, :seq, :version, :unit_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  has_many :course_session_enrollments
  has_many :users, :through => :course_session_enrollments
  attr_accessible :diaspora_login, :shapado_login, :user_name
end

app/models/word.rb
class Word < ActiveRecord::Base
  attr_accessible :fluent_language, :foreign_language, :word_fluent, :word_foreign
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_filter :get_lookups, :only => [:show]
  before_filter :authenticate_user!

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @courses }
    end
  end

  # GET /courses/1
  # GET /courses/1.json
 # def show
 #   @course = Course.find(params[:id])
  #  respond_to do |format|
  #    format.html # show.html.erb
  #    format.json do
  #      @course = Course.find(params[:id])
  #      @units = @course.units.all
  #      @unit_layouts = UnitLayout.where(:unit_id => @units)
  #      @layout_fields = LayoutField.where(:unit_layout_id => @unit_layouts)
  #      response = {:course => @course, :units => @units, :unit_layouts => @unit_layouts, :layout_fields => @layout_fields}
  #      respond_to do |format|
  #        format.json {render :json => response }
  #      end
  #    end
  #  end
#  end
  
  def show
    @course = Course.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.json do
        render :json => @course.to_json(:include => { :units => { :include => {:lessons => {:include => { :lesson_layouts => { :include => [:layout_fields, :layout_tables]}}}}}})
      end
    end
  end

 
  def new
    @course = Course.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @course }
    end
  end

 
  def edit
    @course = Course.find(params[:id])
  end


  def create
    @course = Course.new(params[:course])

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render json: @course, status: :created, location: @course }
      else
        format.html { render action: "new" }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

 
  def update
    @course = Course.find(params[:id])

    respond_to do |format|
      if @course.update_attributes(params[:course])
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course = Course.find(params[:id])
    @course.destroy

    respond_to do |format|
      format.html { redirect_to courses_url }
      format.json { head :no_content }
    end
  end
  
  def json_dump
    @course = Course.find(params[:id])
    @units = Unit.all
    response = {:course => @course, :units => @units }
    respond_to do |format|
      format.json {render :json => response }
    end
  end
  
  private
  def get_lookups
     @course = Course.find(params[:id])
     @course_type = Lookup.find(@course.course_type).lookup_text
     @status = Lookup.find(@course.status).lookup_text
     @language = Lookup.find(@course.course_language).lookup_text
     @target_level = Lookup.find(@course.target_level).lookup_text
  end
 
  
  
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/media_helper.rb
module MediaHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :course_name %><br />
    <%= f.text_field :course_name %>
  </div>
  <div class="field">
    <%= f.label :course_type %><br />
    <%= f.collection_select :course_type, Lookup.find(:all,:conditions => ["model_name = 'course' and field_name = 'course_type'"]), :id, :lookup_text, include_blank: false,:prompt => "Course Type" %>
  </div>
  <div class="field">
    <%= f.label :synopsis %><br />
    <%= f.text_field :synopsis %>
  </div>
  <div class="field">
    <%= f.label :course_language %><br />
    <%= f.collection_select :course_language, Lookup.find(:all,:conditions => ["model_name = 'course' and field_name = 'course_language'"]), :id, :lookup_text, include_blank: false,:prompt => "Language" %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.collection_select :status, Lookup.find(:all,:conditions => ["model_name = 'course' and field_name = 'status'"]), :id, :lookup_text, include_blank: false,:prompt => "Status" %>
  </div>
  <div class="field">
    <%= f.label :target_level %><br />
     <%= f.collection_select :target_level, Lookup.find(:all,:conditions => ["model_name = 'course' and field_name = 'target_level'"]), :id, :lookup_text, include_blank: false,:prompt => "Level" %>
  </div>
  <div class="field">
    <%= f.label :owner %><br />
    <%= f.text_field :owner %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :version %><br />
    <%= f.number_field :version %>
  </div>
  <div class="actions">
    <%= f.submit "#{action_name == 'new' ? 'Create' : 'Update'} Course", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/courses/_units_table.html.erb
<table id="units">
<thead>
  <tr>
    <th>Seq</th>
    <th>Unit Name</th>
    <th>Synopsis</th>
    <th>Unit Type</th>
    <th>Status</th>
    <th>Version</th>
    <th>Course id</th>
    <th></th>
    <th></th>
  </tr>
</thead>
<tbody>  
  <%  @course.units.each do |unit| %>
    <tr>
      <td><%= unit.seq %></td>
      <td><%= link_to unit.unit_name, [@course, unit] %></td>
      <td><%= unit.synopsis %></td>
      <td><%= unit.unit_type %></td>
      <td><%= unit.status %></td>
      <td><%= unit.version %></td>
      <td><%= unit.course_id%></td>
      <td><%= link_to 'Edit', edit_course_unit_path(@course, unit) %></td>
      <td><%= link_to "Delete", [@course, unit], :method => :delete, :confirm => "Are you sure you want to delete this unit?" %></td>
    </tr>
  <% end %>
    <br>
</tbody>
</table>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course, class: 'btn' %>
<%= link_to 'Back', courses_path, class: 'btn' %>

app/views/courses/index.html.erb
<h1>Listing courses</h1>

<table id="courses">
<thead>
  <tr>
    <th>Course name</th>
    <th>Course type</th>
    <th>Synopsis</th>
    <th>Course language</th>
    <th>Status</th>
    <th>Target level</th>
    <th>Owner</th>
    <th>Description</th>
    <th>Version</th>
    <th></th>
    <th></th>
  </tr>
</thead>

<tbody>
<% @courses.each do |course| %>
  <tr>
    <td><%= link_to course.course_name, course %></td>
    <td><%= course.course_type %></td>
    <td><%= course.synopsis %></td>
    <td><%= course.course_language %></td>
    <td><%= course.status %></td>
    <td><%= course.target_level %></td>
    <td><%= course.owner %></td>
    <td><%= course.description %></td>
    <td><%= course.version %></td>
    <td><%= link_to 'Edit', edit_course_path(course), class: 'btn' %></td>
    <td><%= link_to 'Delete', course, method: :delete, data: { confirm: 'Are you sure you want to delete this course?' }, class: 'btn' %></td>
  </tr>
<% end %>
</tbody>
</table>

<br />

<%= link_to 'New Course', new_course_path, class: 'btn' %><br><br />
<%= link_to 'Media Catagories', media_catagories_path, class: 'btn' %>
<%= link_to 'Users', users_path, class: 'btn' %>
<%= link_to 'Sentences', sentences_path, class: 'btn' %>
<%= link_to 'Words', words_path, class: 'btn' %>
<%= link_to 'Badges', badges_path, class: 'btn' %>
<%= link_to 'Tags', tags_path,  class: 'btn' %>

app/views/courses/new.html.erb
<h1>New course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path, class: 'btn' %>

app/views/courses/show.html.erb
<h1>Course</h1>
<p id="notice"><%= notice %></p>

<p>
  <b>Course name:</b>
  <%= @course.course_name %>
</p>

<p>
  <b>Course type:</b>
  <%= @course_type %>
</p>

<p>
  <b>Synopsis:</b>
  <%= @course.synopsis %>
</p>

<p>
  <b>Course language:</b>
  <%= @language %>
</p>

<p>
  <b>Status:</b>
  <%= @status %>
</p>

<p>
  <b>Target level:</b>
  <%= @target_level %>
</p>

<p>
  <b>Owner:</b>
  <%= @course.owner %>
</p>

<p>
  <b>Description:</b>
  <%= @course.description %>
</p>

<p>
  <b>Version:</b>
  <%= @course.version %>
</p>

<%= render 'units_table' %>


<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'New Unit', new_course_unit_path(@course) %> |
<%= link_to 'Back', courses_path %>