config/routes.rb
F4::Application.routes.draw do

  devise_for :users

  resources :badges

  resources :users

  resources :tags

  resources :sentences

  resources :words

  resources :lookups

  resources :courses do
    resources :units
    resources :course_sessions
  end
  
  resources :course_sessions do
    resources :course_session_enrollments
  end
  
  
  resources :units do
    resources :lessons
  end
  
  resources :lessons do
    resources :lesson_layouts
  end
  
  resources :lesson_layouts do
    resources :layout_fields
    resources :layout_tables
  end
  
  resources :media_catagories do
     resources :media
   end
    
  root :to => 'courses#index'

end

app/models/badge.rb
class Badge < ActiveRecord::Base
  attr_accessible :badge_name
end

app/models/course.rb
class Course < ActiveRecord::Base
  attr_accessible :course_language, :course_name, :course_type, :description, :owner, :status, :synopsis, :target_level, :version
  has_many :units, :dependent => :destroy
  has_many :course_sessions, :dependent => :destroy
end

app/models/layout_field.rb
class LayoutField < ActiveRecord::Base
  belongs_to :lesson_layout
  attr_accessible :field_name, :field_value, :version, :lesson_layout_id
end

app/models/layout_table.rb
class LayoutTable < ActiveRecord::Base
  belongs_to :lesson_layout
  attr_accessible :col1, :col2, :col3, :col4, :row_num, :table_number, :version, :lesson_layout_id
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :unit
  has_many :lesson_layouts, :dependent => :destroy
  attr_accessible :description, :lesson_name, :lesson_type, :seq, :status, :synopsis, :version, :unit_id
end

app/models/lesson_layout.rb
class LessonLayout < ActiveRecord::Base
  belongs_to :lesson
  has_many :layout_fields, :dependent => :destroy
  has_many :layout_tables, :dependent => :destroy
  attr_accessible :device_type, :layout_type, :seq, :version, :lesson_id
end

app/models/lookup.rb
class Lookup < ActiveRecord::Base
  attr_accessible :field_name, :lookup_text, :note, :model_name
  
end

app/models/media.rb
class Media < ActiveRecord::Base
  belongs_to :media_catagory
  has_many :media_sentence_xrefs
  has_many :sentences, :through => :media_sentence_xrefs
  attr_accessible :seq, :description, :file_bitmap, :media_filename, :media_name, :media_catagory_id
end

app/models/sentence.rb
class Sentence < ActiveRecord::Base
  has_many :media_sentence_xrefs
  has_many :media, :through => :media_sentence_xrefs
  has_many :sentence_tag_xrefs
  has_many :tags, :through => :sentence_tag_xrefs
  attr_accessible :language, :sentence
end

app/models/sentence_tag.rb
class SentenceTag < ActiveRecord::Base
  belongs_to :sentence
  attr_accessible :tag
end

app/models/sentence_xref.rb
class SentenceXref < ActiveRecord::Base
  attr_accessible :sentence_from, :sentence_to
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :sentence_tag_xrefs
  has_many :sentences, :through => :sentence_tag_xrefs
  attr_accessible :tag, :tag_system_bitmap, :tag_type
end

app/models/unit.rb
class Unit < ActiveRecord::Base
  belongs_to :course
  #has_many :unit_layouts, :dependent => :destroy
  has_many :lessons, :dependent => :destroy
  attr_accessible :description, :seq, :status, :synopsis, :unit_name, :unit_type, :version, :course_id
end

app/models/unit_layout.rb
class UnitLayout < ActiveRecord::Base
  belongs_to :unit
  has_many :layout_fields, :dependent => :destroy
  has_many :layout_tables, :dependent => :destroy
  attr_accessible :device_type, :layout_type, :seq, :version, :unit_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  has_many :course_session_enrollments
  has_many :users, :through => :course_session_enrollments
  attr_accessible :diaspora_login, :shapado_login, :user_name
end

app/models/word.rb
class Word < ActiveRecord::Base
  attr_accessible :fluent_language, :foreign_language, :word_fluent, :word_foreign
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_filter :find_course
  before_filter :find_unit, :only => [:show, :edit, :update, :destroy]
  before_filter :get_lookups, :only => [:show]
  before_filter :authenticate_user!
  
  def new
    @unit = @course.units.build
  end
  
  def create
    @unit = @course.units.build(params[:unit])
    if @unit.save
      flash[:notice] = "Unit has been created."
      redirect_to [@course, @unit]
    else
      flash[:alert] = "Unit could not be created."
      render :actions => "new"
    end
  end
  
  def show
  end
  
  def update
     respond_to do |format|
       if @unit.update_attributes(params[:unit])
         format.html { redirect_to @unit, notice: 'Unit was successfully updated.' }
         format.json { head :no_content }
       else
         format.html { render action: "edit" }
         format.json { render json: @unit.errors, status: :unprocessable_entity }
       end
     end
   end
  
  
  def destroy
    @unit = Unit.find(params[:id])
    @unit.destroy
    redirect_to [@course]
  end
  
  private
  def find_course
    if(params[:course_id].nil?)
      @unit = Unit.find(params[:id])
      @course = Course.find(@unit.course_id)
    else
      @course = Course.find(params[:course_id])
    end  
  end
  
  def find_unit
    @unit = @course.units.find(params[:id])
  end
  
  def get_lookups
    @unit_status = Lookup.where(:id => @unit.status).pluck(:lookup_text)[0]
    @unit_type = Lookup.where(:id => @unit.unit_type).pluck(:lookup_text)[0]
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/media_helper.rb
module MediaHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/units/_form.html.erb
<%= form_for [@course, @unit] do |f| %>
  <div class="field">
    <%= f.label :seq %>
    <%= f.text_field :seq %><br/>
  </div>
  <div class="field">
    <%= f.label :unit_name %>
    <%= f.text_field :unit_name %><br/>
  </div>
  <div class="field">
    <%= f.label :synopsis %>
    <%= f.text_field :synopsis %><br/>
  </div>
  <div class="field">
    <%= f.label :unit_type %>
    <%= f.collection_select :unit_type, Lookup.find(:all,:conditions => ["model_name = 'unit' and field_name = 'unit_type'"]), :id, :lookup_text, include_blank: false,:prompt => "Unit Type" %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.collection_select :status, Lookup.find(:all,:conditions => ["model_name = 'unit' and field_name = 'status'"]), :id, :lookup_text, include_blank: false,:prompt => "Status" %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/units/_lessons_table.html.erb
<table id="lessons">
<thead>
  <tr>
    <th>Seq</th>
    <th>Lesson Name</th>
    <th>Synopsis</th>
    <th>Lesson Type</th>
    <th>Status</th>
    <th>Version</th>
    <th>Course id</th>
    <th></th>
    <th></th>
  </tr>
</thead>
<tbody>  
  <%  @unit.lessons.each do |lesson| %>
    <tr>
      <td><%= lesson.seq %></td>
      <td><%= link_to lesson.lesson_name, [@unit, lesson] %></td>
      <td><%= lesson.synopsis %></td>
      <td><%= lesson.lesson_type %></td>
      <td><%= lesson.status %></td>
      <td><%= lesson.version %></td>
      <td><%= lesson.unit_id%></td>
      <td><%= link_to 'Edit', edit_unit_lesson_path(@unit, lesson) %></td>
      <td><%= link_to "Delete", [@unit, lesson], :method => :delete, :confirm => "Are you sure you want to delete this lesson?" %></td>
    </tr>
  <% end %>
    <br>
</tbody>
</table>

app/views/units/edit.html.erb
<h1>Editing Unit</h1>

<%= render 'form' %>

<br>

<%= link_to 'Back', course_unit_path(@course, @unit) %>

app/views/units/new.html.erb
<h2>New Unit</h2>

<%= render "form"%>

app/views/units/show.html.erb
<h1>Unit</h1>
<div id="unit">
  <p>
    <b>Unit:</b>
    <%= @unit.unit_name %>
  </p>
  <p>
    <b>Unit Type:</b>
    <%= @unit_type %>
  </p>
  <p>
    <b>Unit Status:</b>
    <%= @unit_status %>
  </p>
  <p>
    <b>Synopsis:</b>
    <%= @unit.synopsis %>
  </p>
  
</div>


<%= render 'lessons_table' %>

<%= link_to 'Back', course_path(@course) %> |
<%= link_to "Edit Unit", [:edit, @course, @unit] %> |
<%= link_to 'New Lesson', new_unit_lesson_path(@unit) %>