config/routes.rb
F4::Application.routes.draw do

  devise_for :users

  resources :badges

  resources :users

  resources :tags

  resources :sentences

  resources :words

  resources :lookups

  resources :courses do
    resources :units
    resources :course_sessions
  end
  
  resources :course_sessions do
    resources :course_session_enrollments
  end
  
  
  resources :units do
    resources :lessons
  end
  
  resources :lessons do
    resources :lesson_layouts
  end
  
  resources :lesson_layouts do
    resources :layout_fields
    resources :layout_tables
  end
  
  resources :media_catagories do
     resources :media
   end
    
  root :to => 'courses#index'

end

app/models/badge.rb
class Badge < ActiveRecord::Base
  attr_accessible :badge_name
end

app/models/course.rb
class Course < ActiveRecord::Base
  attr_accessible :course_language, :course_name, :course_type, :description, :owner, :status, :synopsis, :target_level, :version
  has_many :units, :dependent => :destroy
  has_many :course_sessions, :dependent => :destroy
end

app/models/layout_field.rb
class LayoutField < ActiveRecord::Base
  belongs_to :lesson_layout
  attr_accessible :field_name, :field_value, :version, :lesson_layout_id
end

app/models/layout_table.rb
class LayoutTable < ActiveRecord::Base
  belongs_to :lesson_layout
  attr_accessible :col1, :col2, :col3, :col4, :row_num, :table_number, :version, :lesson_layout_id
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :unit
  has_many :lesson_layouts, :dependent => :destroy
  attr_accessible :description, :lesson_name, :lesson_type, :seq, :status, :synopsis, :version, :unit_id
end

app/models/lesson_layout.rb
class LessonLayout < ActiveRecord::Base
  belongs_to :lesson
  has_many :layout_fields, :dependent => :destroy
  has_many :layout_tables, :dependent => :destroy
  attr_accessible :device_type, :layout_type, :seq, :version, :lesson_id
end

app/models/lookup.rb
class Lookup < ActiveRecord::Base
  attr_accessible :field_name, :lookup_text, :note, :model_name
  
end

app/models/media.rb
class Media < ActiveRecord::Base
  belongs_to :media_catagory
  has_many :media_sentence_xrefs
  has_many :sentences, :through => :media_sentence_xrefs
  attr_accessible :seq, :description, :file_bitmap, :media_filename, :media_name, :media_catagory_id
end

app/models/sentence.rb
class Sentence < ActiveRecord::Base
  has_many :media_sentence_xrefs
  has_many :media, :through => :media_sentence_xrefs
  has_many :sentence_tag_xrefs
  has_many :tags, :through => :sentence_tag_xrefs
  attr_accessible :language, :sentence
end

app/models/sentence_tag.rb
class SentenceTag < ActiveRecord::Base
  belongs_to :sentence
  attr_accessible :tag
end

app/models/sentence_xref.rb
class SentenceXref < ActiveRecord::Base
  attr_accessible :sentence_from, :sentence_to
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :sentence_tag_xrefs
  has_many :sentences, :through => :sentence_tag_xrefs
  attr_accessible :tag, :tag_system_bitmap, :tag_type
end

app/models/unit.rb
class Unit < ActiveRecord::Base
  belongs_to :course
  #has_many :unit_layouts, :dependent => :destroy
  has_many :lessons, :dependent => :destroy
  attr_accessible :description, :seq, :status, :synopsis, :unit_name, :unit_type, :version, :course_id
end

app/models/unit_layout.rb
class UnitLayout < ActiveRecord::Base
  belongs_to :unit
  has_many :layout_fields, :dependent => :destroy
  has_many :layout_tables, :dependent => :destroy
  attr_accessible :device_type, :layout_type, :seq, :version, :unit_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  has_many :course_session_enrollments
  has_many :users, :through => :course_session_enrollments
  attr_accessible :diaspora_login, :shapado_login, :user_name
end

app/models/word.rb
class Word < ActiveRecord::Base
  attr_accessible :fluent_language, :foreign_language, :word_fluent, :word_foreign
end

app/controllers/lesson_layouts_controller.rb
class LessonLayoutsController < ApplicationController
  before_filter :find_lesson
  before_filter :find_lesson_layout, :only => [:show, :edit, :update, :destroy]
  before_filter :get_lookups, :only => [:show]
  before_filter :authenticate_user!
  
  def new
    @lesson_layout = @lesson.lesson_layouts.build
  end
  
  def create
    @lesson_layout = @lesson.lesson_layouts.build(params[:lesson_layout])
    if @lesson_layout.save
      flash[:notice] = "Lesson Layout has been created."
      redirect_to [@lesson, @lesson_layout]
    else
      flash[:alert] = "Lesson Layout could not be created."
      render :actions => "new"
    end
  end
  
  def show
  end
  
  def update
     respond_to do |format|
       if @lesson_layout.update_attributes(params[:lesson_layout])
         format.html { redirect_to @lesson_lesson_layout, notice: 'Lesson Layout was successfully updated.' }
         format.json { head :no_content }
       else
         format.html { render action: "edit" }
         format.json { render json: @lesson_layout.errors, status: :unprocessable_entity }
       end
     end
   end
  
  def destroy
     @lesson_layout = LessonLayout.find(params[:id])
     @lesson_layout.destroy
     redirect_to [@lesson]
   end
  
  private
  def find_lesson
    if(params[:lesson_id].nil?)
      @lesson_layout = LessonLayout.find(params[:id])
      @lesson = Lesson.find(@lesson_layout.lesson_id)
    else
      @lesson = Lesson.find(params[:lesson_id])
    end
  end
  
  def find_lesson_layout
    @lesson_layout = @lesson.lesson_layouts.find(params[:id])
  end
  
  private
  def get_lookups
    @device_type = Lookup.where(:id => @lesson_layout.device_type).pluck(:lookup_text)[0]
    @layout_type = Lookup.where(:id => @lesson_layout.layout_type).pluck(:lookup_text)[0]
  end
end

app/helpers/lesson_layouts_helper.rb
module LessonLayoutsHelper
end

app/helpers/media_helper.rb
module MediaHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/lesson_layouts/_form.html.erb
<%= form_for [@lesson, @lesson_layout] do |f| %>
  <div class="field">
    <%= f.label :device_type %>
    <%= f.collection_select :device_type, Lookup.find(:all,:conditions => ["model_name = 'lesson_layout' and field_name = 'device_type'"]), :id, :lookup_text, include_blank: false,:prompt => "Device" %>
  </div>  
  <div class="field">
    <%= f.label :seq %>
    <%= f.text_field :seq %><br/>
  </div>
  <div class="field">
    <%= f.label :layout_type %>
    <%= f.collection_select :layout_type, Lookup.find(:all,:conditions => ["model_name = 'lesson_layout' and field_name = 'layout_type'"]), :id, :lookup_text, include_blank: false,:prompt => "Layout" %>
  </div>
  <div class="field">
     <%= f.label :version %><br />
     <%= f.number_field :version %>
   </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lesson_layouts/_layout_fields_table.html.erb
<h1>Field Data</h1>
<table id="field_data">
  <thead>
  <tr>
    <th>Field Name</th>
    <th>Field Value</th>
    <th>Version</th>
    <th></th>
    <th></th>
  </tr>
  </thead>
<tbody>  
<% @lesson_layout.layout_fields.each do |layout_field| %>
  <tr>
    <td><%= layout_field.field_name %></td>
    <td><%= layout_field.field_value %></td>
    <td><%= layout_field.version %></td>
    <td><%= link_to 'Edit', edit_lesson_layout_layout_field_path(@lesson_layout, layout_field ) %></td>
    <td><%= link_to "Delete", [@lesson_layout, layout_field], :method => :delete, :confirm => "Are you sure you want to delete this layout field?" %></td>
  </tr>
<% end %>
</tbody>
</table>

<br />

app/views/lesson_layouts/_layout_tables_table.html.erb
<h1>Table Data</h1>
<table id="table_data">
  <thead>
  <tr>
    <th>Table Number</th>
    <th>Row</th>
    <th>Column 1</th>
    <th>Column 2</th>
    <th>Column 3</th>
    <th>Column 4</th>
    <th>Version</th>
    <th></th>
    <th></th>
  </tr>
  </thead>
<tbody>  
<% @lesson_layout.layout_tables.each do |layout_table| %>
  <tr>
    <td><%= layout_table.table_number %></td>
    <td><%= layout_table.row_num %></td>
    <td><%= layout_table.col1 %></td>
    <td><%= layout_table.col2 %></td>
    <td><%= layout_table.col3 %></td>
    <td><%= layout_table.col4 %></td>
    <td><%= layout_table.version %></td>
    <td><%= link_to 'Edit', edit_lesson_layout_layout_table_path(@lesson_layout, layout_table ) %></td>
    <td><%= link_to "Delete", [@lesson_layout, layout_table], :method => :delete, :confirm => "Are you sure you want to delete this layout table?" %></td>
  </tr>
<% end %>
</tbody>
</table>

<br />

app/views/lesson_layouts/edit.html.erb
<h1>Editing Lesson Layout</h1>

<%= render 'form' %>

<br>

<%= link_to 'Back', lesson_path(@lesson) %>

app/views/lesson_layouts/new.html.erb
<h2>New Lesson Layout</h2>

<%= render "form"%>

app/views/lesson_layouts/show.html.erb
<h1>Lesson Layout</h1>
<div id="lesson_layout">
  <h2>Lesson Layout</h2>
  <p>
    <b>Seq:</b>
    <%= @lesson_layout.seq %>
  </p>
  <p>
    <b>Device Type:</b>
    <%= @device_type %>
  </p>
  <p>
    <b>Layout Type:</b>
    <%= @layout_type %>
  </p>
  <p>
    <b>Version:</b>
    <%= @lesson_layout.version %>
  </p>
</div>

<% case @layout_type %>
<% when "iPhone Learn Type 1", "iPhone Learn Type 2" %>
  <%= render 'layout_fields_table' %>
  <%= link_to 'Back', lesson_path(@lesson) %> |
  <%= link_to "Edit Lesson Layout", [:edit, @lesson, @lesson_layout] %> |
  <%= link_to 'New Layout Field', new_lesson_layout_layout_field_path(@lesson_layout) %>
<% when "iPhone Learn Type 3", "iPhone Learn Type 4", "iPhone Learn Type 5" %>
  <%= render 'layout_tables_table' %>
  <%= link_to 'Back', lesson_path(@lesson) %> |
  <%= link_to "Edit Lesson Layout", [:edit, @lesson, @lesson_layout] %> |
  <%= link_to 'New Layout Table', new_lesson_layout_layout_table_path(@lesson_layout) %>
<% end %>