config/routes.rb
F4::Application.routes.draw do

  devise_for :users

  resources :badges

  resources :users

  resources :tags

  resources :sentences

  resources :words

  resources :lookups

  resources :courses do
    resources :units
    resources :course_sessions
  end
  
  resources :course_sessions do
    resources :course_session_enrollments
  end
  
  
  resources :units do
    resources :lessons
  end
  
  resources :lessons do
    resources :lesson_layouts
  end
  
  resources :lesson_layouts do
    resources :layout_fields
    resources :layout_tables
  end
  
  resources :media_catagories do
     resources :media
   end
    
  root :to => 'courses#index'

end

app/models/badge.rb
class Badge < ActiveRecord::Base
  attr_accessible :badge_name
end

app/models/course.rb
class Course < ActiveRecord::Base
  attr_accessible :course_language, :course_name, :course_type, :description, :owner, :status, :synopsis, :target_level, :version
  has_many :units, :dependent => :destroy
  has_many :course_sessions, :dependent => :destroy
end

app/models/layout_field.rb
class LayoutField < ActiveRecord::Base
  belongs_to :lesson_layout
  attr_accessible :field_name, :field_value, :version, :lesson_layout_id
end

app/models/layout_table.rb
class LayoutTable < ActiveRecord::Base
  belongs_to :lesson_layout
  attr_accessible :col1, :col2, :col3, :col4, :row_num, :table_number, :version, :lesson_layout_id
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :unit
  has_many :lesson_layouts, :dependent => :destroy
  attr_accessible :description, :lesson_name, :lesson_type, :seq, :status, :synopsis, :version, :unit_id
end

app/models/lesson_layout.rb
class LessonLayout < ActiveRecord::Base
  belongs_to :lesson
  has_many :layout_fields, :dependent => :destroy
  has_many :layout_tables, :dependent => :destroy
  attr_accessible :device_type, :layout_type, :seq, :version, :lesson_id
end

app/models/lookup.rb
class Lookup < ActiveRecord::Base
  attr_accessible :field_name, :lookup_text, :note, :model_name
  
end

app/models/media.rb
class Media < ActiveRecord::Base
  belongs_to :media_catagory
  has_many :media_sentence_xrefs
  has_many :sentences, :through => :media_sentence_xrefs
  attr_accessible :seq, :description, :file_bitmap, :media_filename, :media_name, :media_catagory_id
end

app/models/media_catagory.rb
class MediaCatagory < ActiveRecord::Base
  has_many :media, :dependent => :destroy
  attr_accessible :description, :media_cat, :seq, :version
end

app/models/sentence.rb
class Sentence < ActiveRecord::Base
  has_many :media_sentence_xrefs
  has_many :media, :through => :media_sentence_xrefs
  has_many :sentence_tag_xrefs
  has_many :tags, :through => :sentence_tag_xrefs
  attr_accessible :language, :sentence
end

app/models/sentence_tag.rb
class SentenceTag < ActiveRecord::Base
  belongs_to :sentence
  attr_accessible :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :sentence_tag_xrefs
  has_many :sentences, :through => :sentence_tag_xrefs
  attr_accessible :tag, :tag_system_bitmap, :tag_type
end

app/models/unit.rb
class Unit < ActiveRecord::Base
  belongs_to :course
  #has_many :unit_layouts, :dependent => :destroy
  has_many :lessons, :dependent => :destroy
  attr_accessible :description, :seq, :status, :synopsis, :unit_name, :unit_type, :version, :course_id
end

app/models/unit_layout.rb
class UnitLayout < ActiveRecord::Base
  belongs_to :unit
  has_many :layout_fields, :dependent => :destroy
  has_many :layout_tables, :dependent => :destroy
  attr_accessible :device_type, :layout_type, :seq, :version, :unit_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  has_many :course_session_enrollments
  has_many :users, :through => :course_session_enrollments
  attr_accessible :diaspora_login, :shapado_login, :user_name
end

app/models/word.rb
class Word < ActiveRecord::Base
  attr_accessible :fluent_language, :foreign_language, :word_fluent, :word_foreign
end

app/controllers/media_catagories_controller.rb
class MediaCatagoriesController < ApplicationController
  before_filter :authenticate_user!

  # GET /media_catagories
  # GET /media_catagories.json
  def index
    @media_catagories = MediaCatagory.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @media_catagories }
    end
  end

  # GET /media_catagories/1
  # GET /media_catagories/1.json
  def show
    @media_catagory = MediaCatagory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @media_catagory }
    end
  end

  # GET /media_catagories/new
  # GET /media_catagories/new.json
  def new
    @media_catagory = MediaCatagory.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @media_catagory }
    end
  end

  # GET /media_catagories/1/edit
  def edit
    @media_catagory = MediaCatagory.find(params[:id])
  end

  # POST /media_catagories
  # POST /media_catagories.json
  def create
    @media_catagory = MediaCatagory.new(params[:media_catagory])

    respond_to do |format|
      if @media_catagory.save
        format.html { redirect_to @media_catagory, notice: 'Media catagory was successfully created.' }
        format.json { render json: @media_catagory, status: :created, location: @media_catagory }
      else
        format.html { render action: "new" }
        format.json { render json: @media_catagory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /media_catagories/1
  # PUT /media_catagories/1.json
  def update
    @media_catagory = MediaCatagory.find(params[:id])

    respond_to do |format|
      if @media_catagory.update_attributes(params[:media_catagory])
        format.html { redirect_to @media_catagory, notice: 'Media catagory was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @media_catagory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /media_catagories/1
  # DELETE /media_catagories/1.json
  def destroy
    @media_catagory = MediaCatagory.find(params[:id])
    @media_catagory.destroy

    respond_to do |format|
      format.html { redirect_to media_catagories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/media_catagories_helper.rb
module MediaCatagoriesHelper
end

app/helpers/media_helper.rb
module MediaHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/media_catagories/_form.html.erb
<%= form_for(@media_catagory) do |f| %>
  <% if @media_catagory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@media_catagory.errors.count, "error") %> prohibited this media_catagory from being saved:</h2>

      <ul>
      <% @media_catagory.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :seq %><br />
    <%= f.number_field :seq %>
  </div>
  <div class="field">
    <%= f.label :media_cat %><br />
    <%= f.text_field :media_cat %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :version %><br />
    <%= f.number_field :version %>
  </div>

  <div class="actions">
    <%= f.submit "#{action_name == 'new' ? 'Create' : 'Update'} Media catagory", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/media_catagories/_media_table.html.erb
<table id="media">
<thead>
  <tr>
    <th>Seq</th>
    <th>Media Name</th>
    <th>Media Filename</th>
    <th></th>
    <th></th>
  </tr>
</thead>
<tbody>  
  <%  @media_catagory.media.each do |media| %>
    <tr>
      <td><%= media.seq %></td>
      <td><%= link_to media.media_name, [@media_catagory, media] %></td>
      <td><%= media.media_filename %></td>
      <td><%= link_to 'Edit', edit_media_catagory_media_path(@media_catagory, media), class: 'btn' %></td>
      <td><%= link_to "Delete", [@media_catagory, media], :method => :delete, :confirm => "Are you sure you want to delete this Media?",  class: 'btn' %></td>
    </tr>
  <% end %>
    <br>
</tbody>
</table>

app/views/media_catagories/edit.html.erb
<h1>Editing media_catagory</h1>

<%= render 'form' %>

<%= link_to 'Show', @media_catagory, class: 'btn' %>
<%= link_to 'Back', media_catagories_path, class: 'btn' %>

app/views/media_catagories/index.html.erb
<h1>Listing media_catagories</h1>


<table id="media_catagories">
<thead>
  <tr>
    <th>Seq</th>
    <th>Media cat</th>
    <th>Description</th>
    <th>Version</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
</thead>

<tbody>
<% @media_catagories.each do |media_catagory| %>
  <tr>
    <td><%= media_catagory.seq %></td>
    <td><%= media_catagory.media_cat %></td>
    <td><%= media_catagory.description %></td>
    <td><%= media_catagory.version %></td>
    <td><%= link_to 'Show', media_catagory, class: 'btn' %></td>
    <td><%= link_to 'Edit', edit_media_catagory_path(media_catagory), class: 'btn' %></td>
    <td><%= link_to 'Destroy', media_catagory, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn' %></td>
  </tr>
<% end %>
</tbody>
</table>

<br />

<%= link_to 'New Media Catagory', new_media_catagory_path, class: 'btn' %>
<%= link_to 'Courses', courses_path, class: 'btn' %>

app/views/media_catagories/new.html.erb
<h1>New media_catagory</h1>

<%= render 'form' %>

<%= link_to 'Back', media_catagories_path, class: 'btn' %>

app/views/media_catagories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Seq:</b>
  <%= @media_catagory.seq %>
</p>

<p>
  <b>Media cat:</b>
  <%= @media_catagory.media_cat %>
</p>

<p>
  <b>Description:</b>
  <%= @media_catagory.description %>
</p>

<p>
  <b>Version:</b>
  <%= @media_catagory.version %>
</p>

<%= render 'media_table' %>

<br>
<%= link_to 'Edit', edit_media_catagory_path(@media_catagory), class: 'btn' %>
<%= link_to 'New Media Catagory', new_media_catagory_media_path(@media_catagory), class: 'btn' %>
<%= link_to 'Back', media_catagories_path, class: 'btn' %>